#!/usr/bin/env node
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { createGenerator } from '@unocss/core';
import { defineConfig } from 'unocss';
import presetUno from '@unocss/preset-uno';
import { transformerVariantGroup, transformerDirectives } from 'unocss';
import { shortcuts } from '../uno-config/theme/shortcuts/index.ts';
import { theme } from '../uno-config/theme/index.ts';
import { peerSelectorClasses, peerVariant } from '../uno-config/peer-variants.ts';

const OUTPUT = resolve(import.meta.dirname, '../src/styles/sds.css');

// Minimal config: full theme + shortcuts, no icon presets (not needed for CSS generation)
const uno = await createGenerator(
  defineConfig({
    presets: [presetUno()],
    transformers: [transformerVariantGroup(), transformerDirectives()],
    shortcuts,
    theme,
    variants: [peerVariant],
  })
);

// 'peer' bare class + all peer-selector utility classes needed by floating-label inputs
const shortcutKeys = Object.keys(shortcuts);
const classes = new Set([...shortcutKeys, 'peer', ...peerSelectorClasses]);
const { css } = await uno.generate(classes, { preflights: false });

writeFileSync(
  OUTPUT,
  `/* spoko-design-system — generated by pnpm build:css. Do not edit. */\n\n${css}`,
  'utf8'
);

console.log(`✓ src/styles/sds.css (${shortcutKeys.length} shortcuts, ${css.length} bytes)`);
